### ISSUE TITLE
Website version of AutoHotkeyCE

### ISSUE THREAD

**Issue by hi5** [hi5/AutoHotkeyCE#1]
[AutoHotkeyCE-web.zip](https://github.com/hi5/AutoHotkeyCE/files/2358439/AutoHotkeyCE-web.zip)

Includes the following (original, fixed some links, images) pages:

* index.htm
* WorkingCommands.html
* Developerinfo.html
* WorkingDevices.html
* Changelog.html
* TODO.html
* bin\ folder with CAB
* img\ folder with two images

**Comment by joedf** [comment]
Great work, I've set up the gh-pages webpage.
https://ahkscript.github.io/AutoHotkeyCE

I have linked to it on the hompage.

for reference: https://github.com/ahkscript/homepage/issues/30
