### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by azhkprtw** [hi5/AutoHotkeyCE#3]
Hi, is there any source code available for any versions of AutoHotkeyCE?

I have the development tools installed - was interested to see if I could compile it for other architectures

**Comment by hi5** [comment]
Unless the developer Micha turns up I don't think anybody else has a copy of the source code. 

I don't know if it is possible to decompile PocketPC programs, but that might be the only method to get something you might be able to use.

**Comment by azhkprtw** [comment]
Thank you, I may have found Micha - if the same one. I referenced this issue here.

**Comment by azhkprtw** [comment]
I was wrong. I closed the issue - thanks for your help and advice though!
